version: "3.9"
services:
  frontend:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: pruebaTecnica
      working_dir: /app
      volumes:
         - '.:/app'
         - /app/node_modules/ 
      ports:
        - "5173:5173"